# Generated by Django 6.0.5 on 2026-05-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moodtag",
            name="color",
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name="moodtag",
            name="emoji",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
