# Generated by Django 6.0.5 on 2026-05-24 13:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0002_alter_moodtag_color_alter_moodtag_emoji"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aiinsight",
            name="emotions",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="ai_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PROCESSING", "Processing"),
                    ("COMPLETE", "Complete"),
                    ("FAILED", "Failed"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="mood_score",
            field=models.PositiveSmallIntegerField(
                help_text="1 = very low, 10 = excellent",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="moodtag",
            name="emoji",
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name="moodtag",
            name="journal_entry",
            field=models.ManyToManyField(
                blank=True, related_name="tags", to="journal.journalentry"
            ),
        ),
    ]
