# Generated by Django 6.0.5 on 2026-05-26 07:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0003_alter_aiinsight_emotions_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="journalentry",
            name="ai_status",
        ),
        migrations.AlterField(
            model_name="journalentry",
            name="mood_score",
            field=models.PositiveSmallIntegerField(
                help_text="0 = very low, 10 = excellent",
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
    ]
