# Generated by Django 6.0.5 on 2026-05-26 11:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0004_remove_journalentry_ai_status_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReflectionSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("summary", models.TextField()),
                ("average_mood", models.FloatField()),
                ("entries_count", models.PositiveIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("top_emotions", models.JSONField(default=dict)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reflection",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
