# Generated by Django 6.0.5 on 2026-05-26 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0005_reflectionsnapshot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aiinsight",
            name="emotions",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="reflectionsnapshot",
            name="top_emotions",
            field=models.JSONField(default=list),
        ),
    ]
