# Generated by Django 6.0.5 on 2026-05-26 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0006_alter_aiinsight_emotions_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="moodtag",
            name="journal_entry",
        ),
        migrations.AddField(
            model_name="journalentry",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="entries", to="journal.moodtag"
            ),
        ),
    ]
